name: dotnet package

on: 
  push: #update
    branches: 
      - prod

jobs:
  build:
    name: Get DotNet Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Display dotnet version
        run: dotnet --version
